# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-22 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_auto_20160219_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='share_message',
            field=models.TextField(default='\nCheck out this video!\n'),
        ),
    ]
