# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_taggeditem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taggeditem',
            name='tag',
            field=models.SlugField(choices=[('python', 'python'), ('django', 'django'), ('css', 'css'), ('bootstrap', 'bootstrap')]),
        ),
    ]
