# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-08 15:47
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateTimeField(default=datetime.datetime(2016, 3, 8, 15, 47, 22, 404155, tzinfo=utc), verbose_name='Start Date')),
                ('date_end', models.DateTimeField(default=datetime.datetime(2016, 3, 8, 15, 47, 22, 404208, tzinfo=utc), verbose_name='End Date')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
