# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-07 10:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageview',
            name='timestamp',
            field=models.DateField(default=datetime.datetime(2016, 3, 7, 10, 26, 19, 422208, tzinfo=utc)),
        ),
    ]
