# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-07 13:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_auto_20160307_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageview',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 7, 13, 1, 52, 801463, tzinfo=utc)),
        ),
    ]
