# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-08 14:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0007_auto_20160307_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageview',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 8, 14, 9, 10, 867544, tzinfo=utc)),
        ),
    ]
