# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-09 15:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0013_auto_20160309_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageview',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 9, 15, 45, 56, 336696, tzinfo=utc)),
        ),
    ]
