# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-08 14:09
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_end', models.DateTimeField(default=datetime.datetime(2016, 3, 8, 14, 9, 10, 858080, tzinfo=utc))),
                ('date_start', models.DateTimeField(default=datetime.datetime(2016, 3, 8, 14, 9, 10, 858131, tzinfo=utc))),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
