"""

Generated by 'django-admin startproject' using Django 1.9.2.

For more information on this file, see
https://docs.djangoproject.com/en/1.9/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.9/ref/settings/
"""

import os
from django.conf import settings


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True



# Database LOCAL
# https://docs.djangoproject.com/en/1.9/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(settings.BASE_DIR, 'db.sqlite3'),
    }
}







# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.9/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    os.path.join(settings.BASE_DIR, "static", "static_dirs"),
    #'/var/www/static/',
]

STATIC_ROOT = os.path.join(settings.BASE_DIR, "static", "static_root")


MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(settings.BASE_DIR, "static", "media")

#
# # Braintree infos
#
# BRAINTREE_MERCHANT_ID = "<your_merchant_ID>"
# BRAINTREE_PUBLIC_KEY  = "<your_public_key>"
# BRAINTREE_PRIVATE_KEY = "<your_private_key>"
#
#

#
# JWT_AUTH = {
#     'JWT_RESPONSE_PAYLOAD_HANDLER':
#          'videomembership.utils.jwt_response_payload_handler',
#
#     'JWT_EXPIRATION_DELTA': datetime.timedelta(seconds=30000),
# }

